export const journalData: IJournal[] = [
  {
    id: 'profuture-01',
    title: 'Teknoloji ve Dijital Dergisi',
    cover: '/images/journal-cover.png',
    volume: 1,
    issue: 1,
    date: 'Aralık 2022',
    isNew: true,
  },
  {
    id: 'profuture-02',
    title: 'Teknoloji ve Dijital Dergisi',
    cover: '/images/journal-cover.png',
    volume: 1,
    issue: 1,
    date: 'Haziran 2022',
    isNew: false,
  },
  {
    id: 'profuture-03',
    title: 'Teknoloji ve Dijital Dergisi',
    cover: '/images/journal-cover.png',
    volume: 1,
    issue: 1,
    date: 'Temmuz 2022',
    isNew: true,
  },
  {
    id: 'profuture-04',
    title: 'Teknoloji ve Dijital Dergisi',
    cover: '/images/journal-cover.png',
    volume: 1,
    issue: 1,
    date: 'Ağustos 2022',
    isNew: true,
  },
];
